---
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
bundler_args: --without development system_tests
cache: bundler
script: bundle exec rake test
env:
  - PUPPET_GEM_VERSION="~> 3.2.0"
  - PUPPET_GEM_VERSION="~> 3.3.0"
  - PUPPET_GEM_VERSION="~> 3.4.0"
  - PUPPET_GEM_VERSION="~> 3.5.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 3.6.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
  - PUPPET_GEM_VERSION="~> 3.8.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 3.8.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
  - PUPPET_GEM_VERSION="~> 4.0.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 4.1.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 4.2.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 4.3.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 4.4.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 4.5.0" STRICT_VARIABLES=yes
matrix:
  fast_finish: true
  exclude:
  # Ruby 2.1.0
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 3.2.0"
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 3.3.0"
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 3.4.0"
